### ISSUE TITLE
Ask for password if needed

### ISSUE THREAD

**Issue by staeglis** [nextcloud/user_saml#330] opened 2019-05-01 10:19 UTC
### Steps to reproduce
1. Login via SAML
2. Try to access something that needs the backend (LDAP) password: E.g. mail app, samba share that's configured to use the session credentials

### Expected behaviour
Nextcloud asks for the user password for getting access to e.g. the mails.

### Actual behaviour
Nextcloud throws an error message

### Server configuration

**Nextcloud version:**  15.0.7

**Comment by pierreozoux** [comment] 2024-08-20 07:35
This is a duplicate of https://github.com/nextcloud/user_saml/issues/309

It has been resolved by https://github.com/nextcloud/server/pull/43942

And should be shipped in v30!

Have a nice day!

**Closed by pierreozoux** 2024-08-20 07:35 UTC
