### ISSUE TITLE
Users can't log out

### ISSUE THREAD

**Issue by KroniK907** [nextcloud/user_saml#170] opened 2017-12-28 19:01 UTC
I just updated nextcloud to 12.0.4 and the user_saml plugin to version 1.4.0

After this update, users are no longer able to log out. 

The log out option is no longer in the settings menu found at the top right hand corner of all pages. In addition to this, if a user logs out of their IdP account they remain logged in to nextcloud. 

I am using this plugin with GSuite as my IdP, and logging out of my google account does not log me out of nextcloud. I have to manually delete my cookies to log out.

**Comment by MorrisJobke** [comment] 2018-01-02 14:42
Duplicate of the multiple logout related issues: https://github.com/nextcloud/user_saml/issues?utf8=✓&q=is%3Aissue+is%3Aopen++logout

I will close this for now and we should look into those dedicated enhancement requests

**Closed by MorrisJobke** 2018-01-02 14:42 UTC

**Comment by KroniK907** [comment] 2018-01-04 02:01
Not sure which topic it might be relevant to, but I found that the SLO url had been removed, and once an SLO url had been provided in the SAML authentication settings page, the logout button has re-appeared and works perfectly well for SAML users.
