### ISSUE TITLE
Link to admin manual leads nowhere in NC14

### ISSUE THREAD

**Issue by va1entin** [nextcloud/user_saml#294] opened 2019-01-09 12:02 UTC
Not sure if this is the right repo for such an issue. Sorry, if I'm wrong here!
I only included the NC version below, because the other info is probably not relevant. If it is, I'll gladly supply it.

## Details
The link to the admin manual for the user_saml app leads nowhere in NC 14: https://docs.nextcloud.com/server/13/admin_manual/configuration_server/sso_configuration.html

The last admin manual version that contains docs about sso configuration seems to be for NC 12: https://docs.nextcloud.com/server/12/admin_manual/configuration_server/sso_configuration.html
I couldn't find 

## Steps to reproduce

1. Open "Apps"
2. Click on "SSO & SAML authentication"
3. Click on link to admin manual

### Expected behaviour
Link leads to current docs

### Actual behaviour
`File not found`

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 14.0.4

**Where did you install Nextcloud from:**

**Comment by va1entin** [comment] 2019-01-09 13:39
Just found #244 which points out that the docs are now behind a paywall. That explains why I couldn't find them in the admin manual.

I hope that this isn't the beginning of a descent back into open core, as it happened with OwnCloud. Anyway sorry for the double issue. I'll keep this open for now because the actual issue is still valid.

**Comment by erosinger** [comment] 2019-03-04 13:43
I experience the same issue and am sad seeing the docs hidden behind a paywall. Especially something that offers so much benefits for integration, which is a major concern when deciding to migrate to Nextcloud.

**Comment by wiswedel** [comment] 2019-10-10 11:53
duplicate of #244

**Closed by wiswedel** 2019-10-10 11:53 UTC
