### ISSUE TITLE
Allow but hide direct login

### ISSUE THREAD

**Issue by rullzer** [nextcloud/user_saml#262] opened 2018-11-09 14:21 UTC
We have the option to allow direct logins. Which is great. But often this is only used as a fallback for admins.

It would make sense to have an option to hide this. So for normal user it just does normal IDP selection (and direct redirect for all users).

But then either have a special flag `?admin=true` or a special endpoint to allow direct logins.

This way it won't confuse normal users. But will make it possible for admins to login.

CC: @MorrisJobke  @schiessle

**Comment by posledov** [comment] 2018-12-11 11:42
See #284  :smiley:

**Comment by MorrisJobke** [comment] 2019-01-03 12:43
I would say that this ticket is a duplicate of #126

Closing thus.

**Closed by MorrisJobke** 2019-01-03 12:43 UTC
Labels: enhancement
