### ISSUE TITLE
($password) must be of type string, null given, called in 

### ISSUE THREAD

**Issue by its-dblexchange** [nextcloud/user_saml#716] opened 2023-04-26 21:50 UTC
```
"25.0.6.1","exception":{"Exception":"TypeError","Message":"OCA\\Password_Policy\\ComplianceService::entryControl(): Argument #2 ($password) must be of type string, null given, called in /snap/nextcloud/34542/htdocs/apps/password_policy/lib/Listener/BeforeUserLoggedInEventListener.php on line 45","Code":0,"Trace":[{"file":"/snap/nextcloud/34542/htdocs/apps/password_policy/lib/Listener/BeforeUserLoggedInEventListener.php","line":45,"function":"entryControl","class":"OCA\\Password_Policy\\ComplianceService","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/EventDispatcher/ServiceEventListener.php","line":87,"function":"handle","class":"OCA\\Password_Policy\\Listener\\BeforeUserLoggedInEventListener","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/legacy/OC_User.php","line":192,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/snap/nextcloud/34542/htdocs/lib/private/legacy/OC_User.php","line":243,"function":"loginWithApache","class":"OC_User","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/snap/nextcloud/34542/htdocs/lib/base.php","line":1103,"function":"handleApacheAuth","class":"OC_User","type":"::"},{"file":"/snap/nextcloud/34542/htdocs/lib/base.php","line":1037,"function":"handleLogin","class":"OC","type":"::"},{"file":"/snap/nextcloud/34542/htdocs/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/snap/nextcloud/34542/htdocs/apps/password_policy/lib/ComplianceService.php","Line":90,"CustomMessage":"--"}}

```

Thanks for reporting issues back to Nextcloud! This is the issue tracker of the User SAML app, if you have any support question please check out https://help.nextcloud.com/

Find other components at https://github.com/nextcloud/core/blob/master/CONTRIBUTING.md#guidelines

To make it possible for us to help you please fill out below information carefully.
-->
### Steps to reproduce
1.try to log in using SAML
2.error appears one you log in
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nmeyer00** [comment] 2023-04-28 11:17
I think it has to do with the "password_policy" app.

After disabling it with , the login with SAML should work again.

"sudo -u www-data php ./occ app:disable password_policy"

**Comment by duritong** [comment] 2023-05-03 19:09
I can confirm the issue and that disabling the password_policy app fixes it.

The issue leads to and endless redirect...

**Comment by tamahau30494** [comment] 2023-05-08 19:10
I am also having this issue. The command to disable the password policy worked for me too.

**Comment by solracsf** [comment] 2023-05-12 14:45
Duplicate of https://github.com/nextcloud/user_saml/issues/715

**Closed by solracsf** 2023-05-12 14:45 UTC

**Comment by DarAzizi** [comment] 2023-12-01 19:02
Open Model and add =null to the concerned argument
$password=null
